### ISSUE TITLE
function in Mathematica.

### ISSUE THREAD

**Issue by anilkumarpmnair** [rsmenon/MATLink#100] opened 2018-03-26 12:22 UTC
Actually, I have defined a function in Mathematica.
And using Matlink I am using one script from Matlab in the notebook. I want to call the earlier defined function in that section.
Like transforming variable in Mathematica and send it back to MATLAB via MSet, is there any way to call functions in Mathematica to Matlab?

Thanks for the help.

**Comment by szhorvat** [comment] 2018-03-26 13:24
Duplicate of #99

**Closed as completed by szhorvat** 2018-03-26 13:24 UTC
Labels: duplicate, declined
