### ISSUE TITLE
matlink

### ISSUE THREAD

**Issue by Abdelaala199590** [rsmenon/MATLink#112] opened 2021-09-28 19:15 UTC
How to install matlink please :)

**Comment by Abdelaala199590** [comment] 2021-09-28 19:16
How to install matlink please :)

**Comment by szhorvat** [comment] 2021-09-28 19:29
Installation instructions are on http://matlink.org/

If you have difficulties with installation, please be specific about what did not work.

**Comment by Abdelaala199590** [comment] 2021-09-28 19:43
@szhorvat 
realy i appreciate your comment
i downloaded the zip file but can't use it :(
can you help me ?

**Comment by szhorvat** [comment] 2021-09-28 19:58
We cannot help you unless you explain in clear and precise terms what you did so far and where you got stuck. As I said, the installation instructions are on http://matlink.org/. Follow them step by step. The instructions describe where you need to place the contents of the zip file, after extracting it.

**Comment by Abdelaala199590** [comment] 2021-09-28 20:01
The instructions describe where you need to place the contents of the zip file, after extracting it.
yes this is my problem

**Comment by Abdelaala199590** [comment] 2021-09-28 20:22
can you explain to me the 1st step please 
where is the "PATH environment variable"

**Comment by Abdelaala199590** [comment] 2021-09-28 20:28
"Not connected to the MATLAB engine."
this message appearse to me 
i can't solve it

**Comment by szhorvat** [comment] 2021-09-29 16:02
In order to be able to help you, we need to have an accurate picture of what you are doing and what is happening on your computer. As I said two times above, please describe _in detail_ what you have done (relating it to the context of the installation and troubleshooting instructions on matlink.org), what was the outcome, and what you expected instead.

The procedure to set the PATH environment variable differs between Windows versions. Please google for instructions for your specific windows version, and follow those instructions.

If you still encounter problems after following the installation instructions (including setting PATH) carefully, first read through the troubleshooting page in full. If the problem is nor covered there, show the output of ``MATLink`Developer`GetInfo[]`` as requested on the troubleshooting page.

**Comment by Abdelaala199590** [comment] 2021-10-30 22:41
@szhorvat 
I really thank you, i did all the steps,
but when i excute OpenMATLAB[] in notebook in mathematica, i have this error messege
"the code excution cannot proceed bexause ML323.dll was not found"
what is the solution please !

**Comment by szhorvat** [comment] 2021-10-31 08:32
I cannot tell what is going wrong on your computer unless you provide all information I requested above.

**Comment by szhorvat** [comment] 2021-11-06 11:21
Closing, as there is insufficient information to identify the problem.

**Closed as completed by szhorvat** 2021-11-06 11:21 UTC
